### ISSUE TITLE
"pip install gdown" doesn't work

### ISSUE THREAD

**Issue by zia-hasan** [ServiceNow/azimuth#42]
**Is your feature request related to a problem? Please describe.**
`pip install gdown` doesn't work perhaps due to various dependency mismatches

    Collecting gdown
      Using cached gdown-4.4.0.tar.gz (14 kB)
      Installing build dependencies ... error
      ERROR: Command errored out with exit status 1:
       command: /Users/zia.hasan/anaconda3/bin/python /Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/yl/8d2pf1t54_3gknvrf_qs8_cc0000gp/T/pip-build-env-2rnpl_90/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
           cwd: None
      Complete output (44 lines):
      Traceback (most recent call last):
        File "/Users/zia.hasan/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "/Users/zia.hasan/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
          sys.exit(_main())
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
          command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
          module = importlib.import_module(module_path)
        File "/Users/zia.hasan/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 783, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
          from pip._internal.cli.req_command import RequirementCommand, with_cleanup
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
          from pip._internal.index.package_finder import PackageFinder
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
          from pip._internal.index.collector import parse_links
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
          from pip._vendor import html5lib, requests
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
          from . import utils
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
          from . import certs
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
          from pip._vendor.certifi import where
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
          from .core import contents, where
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
          from importlib.resources import read_text
        File "/Users/zia.hasan/anaconda3/lib/python3.8/importlib/resources.py", line 11, in <module>
          from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/typing.py", line 1359, in <module>
          class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
        File "/Users/zia.hasan/anaconda3/lib/python3.8/site-packages/typing.py", line 1007, in __new__
          self._abc_registry = extra._abc_registry
      AttributeError: type object 'Callable' has no attribute '_abc_registry'
      ----------------------------------------
    ERROR: Command errored out with exit status 1: /Users/zia.hasan/anaconda3/bin/python /Users/zia.hasan/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/yl/8d2pf1t54_3gknvrf_qs8_cc0000gp/T/pip-build-env-2rnpl_90/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Describe the solution you'd like**
Perhaps update the tutorial/documentation to better handle this. poetry dev-dependency?

**Comment by Dref360** [comment]
Right this installs `gdown` as a global dependencies. Can you try the solution [from this thread](https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry)? 

I'll make a PR that explains how to download the file manually as not everyone will be able to download the package.

The file is available on [Google Drive](https://drive.google.com/file/d/1LmP_Y1KGxiOOJrTkXjocLnOgSmhqDRzk/view?usp=sharing). you can then uncompress it to `azimuth_shr` so that you have a folder named `azimuth_shr/files/clinc-demo`.

**Comment by zia-hasan** [comment]
Yes, it works after uninstalling `typing`. Thanks. Yeah, some alternative method or clarification might be better because global dependency install with `gdown` is perhaps not going to work for everyone.

**Comment by Dref360** [comment]
Added instruction in this Discussions: https://github.com/ServiceNow/azimuth/discussions/46

Feedback welcome. I'll add a link in the doc to this discussion.

**Comment by zia-hasan** [comment]
Suggestion: Perhaps you could add a link to this alternate download method as well as [stackovrflow thread](https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry) in the main documentation?
