### ISSUE TITLE
Error running tutorial steps

### ISSUE THREAD

**Issue by zia-hasan** [ServiceNow/azimuth#43]
**Describe the bug**
got the following error while running `make CFG_PATH=/config/development/clinc_dummy/conf.json compose`

          Attaching to azimuth_web_1, azimuth_backend_1
          web_1      | internal/modules/cjs/loader.js:892
          web_1      |   throw err;
          web_1      |   ^
          web_1      |
          web_1      | Error: Cannot find module 'cors'
          web_1      | Require stack:
          web_1      | - /app/server.js
          web_1      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
          web_1      |     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
          web_1      |     at Module.require (internal/modules/cjs/loader.js:961:19)
          web_1      |     at require (internal/modules/cjs/helpers.js:92:18)
          web_1      |     at Object.<anonymous> (/app/server.js:4:14)
          web_1      |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
          web_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
          web_1      |     at Module.load (internal/modules/cjs/loader.js:937:32)
          web_1      |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
          web_1      |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
          web_1      |   code: 'MODULE_NOT_FOUND',
          web_1      |   requireStack: [ '/app/server.js' ]
          web_1      | }
          azimuth_web_1 exited with code 1

**Comment by zia-hasan** [comment]
I can confirm that the instructions don't seem to make it work despite building a docker image etc. I followed all the steps correctly until `make CFG_PATH=/config/development/clinc_dummy/conf.json compose`.  The following step also didn't work initially but I used a separate `conda` environment to run it successfully.

    pip install gdown
    make download_demo
